# Site settings
title: Yi's technical Blog
author: "Yi Fu"
header-img: img/home-bg.jpg
email: yvesfu@gmail.com
keywords: "software engineering, web develpment, design pattern, data scientist"
description: "Lazy, no description"
baseurl: ""
url: "blog.minus1.se"
twitter_username: yvesfu
github_username:  fuyi
facebook_username:  yvesfu
linkedin_user: yvesfu

# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# Gems
gems: [jekyll-paginate]
