# Site settings
title: Yi's technical Blog
author: "Yi Fu"
header-img: img/home-bg.jpg
email: yvesfu@gmail.com
description: "Lazy, no description"
baseurl: ""
url: "blog.minus1.se"
twitter_username: yvesfu
github_username:  fuyi
facebook_username:  yvesfu
linkedin_user: yvesfu

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
